#!/usr/bin/env perl
use Mojolicious::Lite;
use Mojo::JSON qw(decode_json encode_json);
use Mojolicious::Plugin::Authentication;

app->plugin(
    authentication => {
        autoload_user => 1,
        load_user     => sub {
            my ( $app, $uid ) = @_;
            # uid from validate sub, return a user object
            return $uid;
        },
        validate_user => sub {
            my ( $app, $username, $password, $extradata ) = @_;
            # return a uid if validated
            return 1 if ( $username eq 'bender' && $password eq 'bending' );
            return;
        },
    },
);

my $clients = {};

my $dogs = {};

get '/' => sub {
    my $c = shift;
    $c->render( template => 'index' );
};

websocket '/dog' => sub {
    my $c = shift;

    app->log->debug( sprintf 'Client connected: %s', $c->tx );
    my $id = sprintf "%s", $c->tx;
    $clients->{$id} = $c->tx;
    app->log->debug( 'id: ' . $id );

    my $name = $c->tx->connection;
    $dogs->{$id}->{name} = $name;
    $dogs->{$id}->{x} = 10;
    $dogs->{$id}->{y} = 10;

    # Opened
    $c->app->log->debug('WebSocket opened');

    # Allow inactivity indefinitely
    $c->inactivity_timeout(0);

    # Incoming message
    $c->on(
        message => sub {
            my ( $c, $msg ) = @_;
            $c->app->log->debug("incoming: $msg");
            if ( my $j = decode_json $msg ) {
                app->log->debug( $j->{cmd} );
                if ( $j->{cmd} eq 'AUTHENTICATE' ) {
                    $c->authenticate( $j->{name}, $j->{code} );
                }
                if ( $j->{cmd} eq 'DE_AUTHENTICATE' ) {
                    $c->logout();
                    $c->session( expires => 1 );
                }
                if ( $j->{cmd} eq 'up' ){
                  $dogs->{$id}->{y} -= 5;
                }
              $dogs->{ $c->tx }->{is_auth} = $c->is_user_authenticated;
            }
            update_clients();
        }
    );

    # Closed
    $c->on(
        finish => sub {
            my ( $c, $code, $reason ) = @_;
            $c->app->log->debug("WebSocket closed with status $code");
            delete $clients->{$id};
            delete $dogs->{$id};
            update_clients();
        }
    );
};

sub update_clients {
    my (%args) = @_;

    for ( keys %$clients ) {
        $clients->{$_}->send(
            {
                json => {
                    wow  => $clients->{$_}->connection,
                    dogs => $dogs,
                }
            }
        );
    }

    return;
}

app->start;
__DATA__

@@ index.html.ep
% layout 'default';
% title 'mat.chti.me';
<h1>mat.chti.me</h1>
<p id='wow'>wow</p>
<button id='up' onclick="up();">up</button>
<button id='down' onclick="down();">down</button>
<button id='left' onclick="left();">left</button>
<button id='right' onclick="right();">right</button>
<br/>
<canvas id='map' width='640' height='480'></canvas>
<p id='list'>list</p>
<button id='login' onclick="login();">auth</button>
<button id='logout' onclick="logout();">deauth</button>
<input type='text' id='name' value='name'/>
<input type='password' id='code' value='code'/>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head><title><%= title %></title></head>
  <body onload="draw();">
<script>
      var ws = new WebSocket('<%= url_for('dog')->to_abs->scheme('wss') %>');

      var dogs = [];

      // Incoming messages
      ws.onmessage = function (event) {
        var res = JSON.parse(event.data);
        document.getElementById('wow').innerHTML = res.wow;
        document.getElementById('list').innerHTML = '';
        dogs = res.dogs;
        for ( var d in res.dogs ) {
          var dog = document.getElementById(d);
          if ( ! dog ){
            dog = document.createElement("div");
            dog.innerHTML = res.dogs[d].name;
            dog.innerHTML += ' ' + res.dogs[d].is_auth;
            dog.id = res.dogs[d].name;
            document.getElementById('list').appendChild(dog);
          }
        }
        draw();
      };

      // Outgoing messages
      ws.onopen = function (event) {
        ws.send(JSON.stringify({cmd:'init'}));
      };

      // Detect connect close
      ws.onclose = function (event) {
        document.getElementById('wow').innerHTML = 'lost connection <a href="javascript:window.location.href=window.location.href">reload</a>';
      };

      function login() {
        var name = document.getElementById('name').value;
        var code = document.getElementById('code').value;
        var cmd = 'AUTHENTICATE';
        var msg = { 'cmd': cmd, 'name': name, 'code': code };
        ws.send(JSON.stringify(msg));
      }

      function logout() {
        ws.send(JSON.stringify({cmd:'DE_AUTHENTICATE'}));
      }

      function draw() {
        var canvas = document.getElementById('map');
        if (canvas.getContext) {
          var ctx = canvas.getContext("2d");


          ctx.fillStyle = "#DDFFDD";
          ctx.fillRect (0, 0, 640, 480);

          for ( var d in dogs )
          {
            ctx.fillStyle = "rgba(0, 0, 200, 0.5)";
            ctx.fillRect( dogs[d].x, dogs[d].y, 55, 50);
          }
        }
      }

      function up() {
        msg = { 'cmd': 'up' };
        ws.send(JSON.stringify(msg));
      }

    </script>
  <%= content %>🐄</body>
</html>
